{{- if eq (include "twentycrm-chart.bundledDb" .) "true" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "twentycrm-chart.dbName" . }}
  namespace: {{ include "twentycrm-chart.namespace" . }}
  labels:
    {{- include "twentycrm-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgres
      port: {{ .Values.postgresql.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "twentycrm-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: db
{{- end }}
