{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "twentycrm-chart.redisName" . }}
  namespace: {{ include "twentycrm-chart.namespace" . }}
  labels:
    {{- include "twentycrm-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "twentycrm-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
