{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "twentycrm-chart.serviceAccountName" . }}
  namespace: {{ include "twentycrm-chart.namespace" . }}
  labels:
    {{- include "twentycrm-chart.labels" . | nindent 4 }}
  {{- $annotations := merge (deepCopy .Values.serviceAccount.annotations) .Values.commonAnnotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
